### ISSUE TITLE
No option to delete model and script

### ISSUE THREAD

**Issue by rrr-coders** [RedisAI/redisai-py#19]
Please provide an option to execute the redisai cli command `AI.MODELDEL model_key` and `AI.SCRIPTDEL script_key`

**Comment by hhsecond** [comment]
@rrr-coders Thanks for raising the issue. We'll have the new commands integrated to the python client this week.

**Comment by rrr-coders** [comment]
Great to hear that !

**Comment by hhsecond** [comment]
Addressing with #21

**Comment by hhsecond** [comment]
@rrr-coders #21 is merged to master

**Comment by rrr-coders** [comment]
Awesome! Thanks
