### ISSUE TITLE
DAGRUN is not working with RedisAI 1.2.1

### ISSUE THREAD

**Issue by valdemaras-pipiras** [RedisAI/redisai-py#57]
Hi,

Could you give a hand on solving the puzzle?

Such SHELL command executes successfully:

`AI.DAGRUN LOAD 1 "model_2_2021-03-02_input" PERSIST 1 predictions |> AI.MODELRUN "model_2_2021-03-02" INPUTS "model_2_2021-03-02_input" OUTPUTS predictions |> AI.TENSORGET predictions VALUES `

But If I'm executing it redisai.py way:

`dag = redisclient.dag(load=['model_2_2021-03-02_input'], persist=['predictions'])
dag.modelrun('model_2_2021-03-02', inputs=['model_2_2021-03-02_input'], outputs=['predictions'])
predictions = dag.tensorget('predictions').run()`

It fails with the result:

`ResponseError: Invalid DAGRUN command`

**Comment by DvirDukhan** [comment]
@valdemaras-pipiras 
Thanks for reporting, we will submit a fix soon

**Comment by valdemaras-pipiras** [comment]
Thanks @DvirDukhan 
Waiting for the fix.

**Comment by hhsecond** [comment]
@valdemaras-pipiras it's been fixed in the master already. We'll push a patch release today/tomorrow but feel free to use the master meanwhile.

**Comment by hhsecond** [comment]
@valdemaras-pipiras the new version is live in pypi. Let us know if you still have the issue

**Comment by valdemaras-pipiras** [comment]
Everything works like a charm :)
Thanks guys, you are incredible.
